config/routes.rb
CantineApp::Application.routes.draw do

  root to: 'feeds#index'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :entries
  resources :read_entries
  resources :feeds
  resources :users
  resources :subscriptions
  resources :bookmarks

  post 'feeds/:id', to: 'feeds#subscribe', as: :feeds_subscribe

  get 'entries/:id/bookmark', to: 'entries#bookmark', as: :entries_bookmark
  get 'entries/:id/mark_as_read', to: 'entries#mark_as_read', as: :entries_mark_as_read
  get 'feeds/:id/update_entries', to: 'feeds#update_entries', as: :feeds_update_entries

  get 'tagged', to: 'subscriptions#tagged', :as => 'tagged'

  resources :entries do
  get 'page/:page', action: :index, on: :collection
  end

end

app/models/feed.rb
class Feed < ActiveRecord::Base

  attr_accessible :etag, :last_modified, :publisher_url, :title, :url, :feed_url
  has_many :entries, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :users, through: :subscriptions

  def self.parse_fail?(feed)
    feed == 0 || feed == 404 || feed == 408 || feed == 200 || feed == []
  end

  def list_related_feeds(current_user)
    feeds = []
    self.users.each do |user|
      if user != current_user
        user.subscriptions.map do |subscription|
          if subscription.feed != self
          feeds << subscription.feed
          end
        end
      end
    end
    feeds.sort_by { |feed| feed.users.count }
    feeds.uniq
  end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  # GET /feeds
  # GET /feeds.json
  def index
    @feed = Feed.new
    if params[:q]
      q = params[:q]

      @feeds = Feed.search(title_cont: q).result(distinct: true)
      @entries = Entry.search(title_cont: q).result(distinct: true)
      @users = User.search(last_name_cont: q).result(distinct: true)
    else
      @feeds = Feed.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feeds }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    @feed = Feed.find(params[:id])
    @related_feeds = @feed.list_related_feeds(current_user)
    @feed_entries = Entry.where(feed_id: @feed.id).order("updated_at DESC").page(params[:page]).per(10)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.json
  def new
    @feed = Feed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/1/edit
  def edit
    @feed = Feed.find(params[:id])
  end

  # POST /feeds
  # POST /feeds.json
  def create
    Feedzirra::Feed.add_common_feed_element 'image'
    parsed_feed = Feedzirra::Feed.fetch_and_parse(params[:url])
    feed = Feed.new
    if Feed.parse_fail?(parsed_feed)
      redirect_to root_path, notice: 'Invalid URL.'
    else
      if Feed.exists?(feed_url: parsed_feed.feed_url)
        feed = Feed.find(Feed.where("feed_url = '#{parsed_feed.feed_url}'")[0].id)
        current_user.auto_subscribe(feed)
        redirect_to feed
      else
        feed.title = parsed_feed.title
        feed.gu_id = parsed_feed.etag
        feed.feed_url = parsed_feed.feed_url
        feed.image = parsed_feed.image
        feed.last_updated = parsed_feed.last_modified
        feed.save
        current_user.auto_subscribe(feed)

        Entry.update_from_feed(feed.feed_url, feed.id)

        redirect_to root_path
      end
    end
  end

  # PUT /feeds/1
  # PUT /feeds/1.json
  def update
    @feed = Feed.find(params[:id])

    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to @feed, notice: 'Feed successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :no_content }
    end
  end

  def subscribe
    @feed = Feed.find(params[:id])
    if current_user.is_subscribed?(@feed.id)
      redirect_to Feed.find(params[:id])
    else
      @subscription = Subscription.new
      @subscription.user_id = current_user.id
      @subscription.feed_id = params[:id]
      @subscription.save
      redirect_to Feed.find(params[:id])
    end
  end

  def update_entries
    feed = Feed.find(params[:id])
    Entry.update_from_feed(feed.feed_url, feed.id)
    redirect_to feed
  end

end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_feed.html.haml
- if current_user

  .feedtileparent
    .feedtile
      .placeholder= link_to(image_tag("placeholder.png"), feed)
    .feedtiletext
      = link_to "#{feed.title}", feed
      - if current_user && current_user.is_subscribed?(feed.id) != true
        .subscribeicon= link_to image_tag("subscribe.png", alt: "Subscribe", :id => 'subscribe'), feed, method: :subscribe

- else
  = image_tag("landing.png", alt: "Welcome to Canteen", :id => 'landing')

app/views/feeds/_form.html.haml
= form_for @feed do |f|
  - if @feed.errors.any?
    #error_explanation
      %h2= "#{pluralize(@feed.errors.count, "error")} prohibited this feed from being saved:"
      %ul
        - @feed.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :url
    = f.text_field :url, placeholder: "Feed url:"
  .actions
    = f.submit 'Add Feed'

app/views/feeds/index.html.haml
- if current_user

  - if params[:q].present?

    %h2= "Results matching '#{params[:q]}'"

    %h3 Feeds
    - if @feeds.any?
      - @feeds.each do |feed|
        %p= link_to feed.title, feed
    - else
      %em No match found.

    %h3 Entries
    - if @entries.any?
      - @entries.each do |entry|
        %p= link_to entry.title, entry
    - else
      %em No match found.

    %h3 Users
    - if @users.any?
      - @users.each do |user|
        %p= link_to user.first_name, user
    - else
      %em No match found.

  - else
    = render @feeds

- else
  = image_tag("landing.png", alt: "Welcome to Canteen", :id => 'landing')

app/views/feeds/show.html.haml
%p#notice= notice

.feedcontainer
  .feedimagebig
    .placeholderbig= image_tag("placeholder.png")

  .feeddetails
    %h2.title
      = @feed.title
    %p
      = @feed.url
    %p
      -if @feed.last_updated
        %b Last updated:
        %br
        = @feed.last_updated.strftime("%a %d %b %Y")
    - if current_user && current_user.is_subscribed?(@feed.id) != true
      = link_to image_tag("subscribe.png", alt: "Subscribe", :id => 'subscribebig'), @feed, method: :subscribe
    = link_to image_tag("update.png", alt: 'Update', :id => 'update'), feeds_update_entries_path(@feed)

  .userssimilar
    %p.title
      - if @related_feeds != []
        %b Users that subscribe to this are also reading:
        %br
        %br
          - @related_feeds[0..4].each do |feed|
            = link_to feed.title, feed
            %br

.feedentries
  %table
    %tr
      %th
      %th
      %th
      %th
    - @feed_entries.each do |entry|
      %tr
        %td
          - if current_user && current_user.has_read?(entry.id) != true
            .iconleft= link_to image_tag("unread.png", alt: "Unread", :id => 'unread'), entries_mark_as_read_path(entry)
          - if current_user && current_user.has_read?(entry.id)
            .iconleft= link_to image_tag("unread2.png", alt: "Read", :id => 'unread'), entries_mark_as_read_path(entry)
        %td
          - if current_user && current_user.has_bookmarked?(entry.id) != true
            .iconleft= link_to image_tag("bookmark.png", alt: "Bookmark", :id => 'bookmark'), entries_bookmark_path(entry)
          - if current_user && current_user.has_bookmarked?(entry.id)
            .iconleft= link_to image_tag("bookmark2.png", alt: "Bookmark", :id => 'bookmark'), entries_bookmark_path(entry)
        %td
          %strong
            = link_to truncate(entry.title, length: 60), entry
        %td
          = time_ago_in_words(entry.updated_at)
  = paginate @feed_entries