config/routes.rb
CantineApp::Application.routes.draw do

  root to: 'feeds#index'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :entries
  resources :read_entries
  resources :feeds
  resources :users
  resources :subscriptions
  resources :bookmarks

  post 'feeds/:id', to: 'feeds#subscribe', as: :feeds_subscribe

  get 'entries/:id/bookmark', to: 'entries#bookmark', as: :entries_bookmark
  get 'entries/:id/mark_as_read', to: 'entries#mark_as_read', as: :entries_mark_as_read
  get 'feeds/:id/update_entries', to: 'feeds#update_entries', as: :feeds_update_entries

  get 'tagged', to: 'subscriptions#tagged', :as => 'tagged'

  resources :entries do
  get 'page/:page', action: :index, on: :collection
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader

  before_validation :set_default_role

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :bio, :avatar, :email, :role, :password, :password_confirmation, :remember_me, :avatar_cache, :remove_avatar

  has_many :subscriptions, dependent: :destroy
  has_many :read_entries, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  has_many :feeds, through: :subscriptions
  has_many :entries, through: :bookmarks
  has_many :entries, through: :read_entries


  def is_subscribed?(feed_id)
    user_id = self.id
    if Subscription.exists?(user_id: user_id, feed_id: feed_id)
      return true
    end
  end

  def has_bookmarked?(entry_id)
    user_id = self.id
    if Bookmark.exists?(user_id: user_id, entry_id: entry_id)
      return true
    end
  end

  def has_read?(entry_id)
    user_id = self.id
    if ReadEntry.exists?(user_id: user_id, entry_id: entry_id)
      return true
    end
  end

  def auto_subscribe(feed)
    if self.is_subscribed?(feed.id) != true
      @subscription = Subscription.new
      @subscription.user_id = self.id
      @subscription.feed_id = feed.id
      @subscription.save
    end
  end

  def role?(role)
  self.role.to_s == role.to_s
  end

  private
  def set_default_role
    self.role ||= "user"
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def after_destroy_path_for(resource)
    root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/show.html.haml
-if current_user == @user
  .userfeeds
    .profile
      .placeholderavatar= image_tag @user.avatar.thumb
      .profiledetails
        %h2
          =@user.first_name
          =@user.last_name
        %p
          = @user.email
  .userfeeds
    -@current_user.subscriptions.each do |subscription|
      .feedtileparent
        .feedtileprofile
          .placeholder= link_to(image_tag("placeholder.png"), feed_path(subscription.feed))
          %br
        .feedtiletext
          = link_to "#{subscription.feed.title}", feed_path(subscription.feed)
  .userfeeds
    %h4 About Me
    %p
      =@user.bio
    %br
    .iconleft= link_to image_tag("edit.png", alt: "Edit Profile", :id => 'editbig'), edit_user_registration_path
    .iconleft= link_to image_tag("trash.png", alt: "Delete Profile", :id => 'trashbig'), users_path, method: :delete, data: { :confirm => 'Are you sure?' }

-else
  .userfeeds
    .profile
      .placeholderavatar= image_tag @user.avatar.thumb
      .profiledetails
        %h2
          =@user.first_name
          =@user.last_name
        %p
          = @user.email
        %p
          =@user.bio
  %br
  -if @user.first_name != ""
    %h4 #{@user.first_name}'s feeds
  -else
  .userfeeds
    -@user.subscriptions.where("private is not ?", true).each do |subscription|
      .feedtileparent
        .feedtileprofile
          - if subscription.feed.image
            = link_to(image_tag(subscription.feed.image), feed_path(subscription.feed))
          - else
            .placeholder= link_to(image_tag("placeholder.png"), feed_path(subscription.feed))
          %br
        .feedtiletext
          = link_to "#{subscription.feed.title}", feed_path(subscription.feed)
    