config/routes.rb
CantineApp::Application.routes.draw do

  root to: 'feeds#index'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :entries
  resources :read_entries
  resources :feeds
  resources :users
  resources :subscriptions
  resources :bookmarks

  post 'feeds/:id', to: 'feeds#subscribe', as: :feeds_subscribe

  get 'entries/:id/bookmark', to: 'entries#bookmark', as: :entries_bookmark
  get 'entries/:id/mark_as_read', to: 'entries#mark_as_read', as: :entries_mark_as_read
  get 'feeds/:id/update_entries', to: 'feeds#update_entries', as: :feeds_update_entries

  get 'tagged', to: 'subscriptions#tagged', :as => 'tagged'

  resources :entries do
  get 'page/:page', action: :index, on: :collection
  end

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessible :user_id, :feed_id, :tag_list, :private
  belongs_to :user
  belongs_to :feed

  acts_as_taggable_on :tags

 

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  load_and_authorize_resource
  # GET /subscriptions
  # GET /subscriptions.json
  def index

    # add scope for current user in model
    @subscriptions =  User.find(current_user).subscriptions
    @tags = @subscriptions.tag_counts_on(:tags).order('count desc').limit(20)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscriptions }
    end
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subscription }
    end
  end

  # GET /subscriptions/new
  # GET /subscriptions/new.json
  def new
    @subscription = Subscription.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subscription }
    end
  end

  # GET /subscriptions/1/edit
  def edit
    @subscription = Subscription.find(params[:id])
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(params[:subscription])
    @subscription.user_id = current_user.id

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render json: @subscription, status: :created, location: @subscription }
      else
        format.html { render action: "new" }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subscriptions/1
  # PUT /subscriptions/1.json
  def update
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      if @subscription.update_attributes(params[:subscription])
        format.html { redirect_to @subscription.feed, notice: 'Subscription was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to feeds_path }
      format.json { head :no_content }
    end
  end

  def tagged
    if params[:tag].present? 
      @subscriptions = Subscription.tagged_with(params[:tag])
    else 
      @subscriptions = Subscription.all
    end  
  end

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper

include ActsAsTaggableOn::TagsHelper
  
end

app/views/subscriptions/_form.html.haml
.feedcontainer
  .feedimagebig
    .placeholderbig= image_tag("placeholder.png")

  .feeddetails
    %h2.title
      = @subscription.feed.title
    %p
      = @subscription.feed.url
    %p
      -if @feed.last_updated
        %b Last updated:
        %br
        = @subscription.feed.last_updated.strftime("%a %d %b %Y")

= form_for @subscription do |f|
  - if @subscription.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subscription.errors.count, "error")} prohibited this subscription from being saved:"
      %ul
        - @subscription.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :tags
    %br
    = f.text_field :tag_list, id: "taginput", placeholder: "enter tags here, separated by commas"
    %br
    %br
    = f.label "Private Subscription?"
    = f.check_box :private, {}, true, false
    %br
    %br
  .actions
    .submitbutton= f.submit 'Save'

app/views/subscriptions/_subscription.html.haml
#accordion
  - @tags.each do |tag|
    .group
      %h3= tag.name
      - Subscription.tagged_with(tag.name).each do |subscription|

        = link_to truncate(subscription.feed.title), subscription.feed
        .icon= link_to image_tag("trash.png", alt: "Remove subscription", :id => 'trash'), subscription, method: :delete, data: { :confirm => 'Are you sure?' }

        .icon= link_to link_to image_tag("edit.png", alt: "Edit tags", :id => 'edit'), edit_subscription_path(subscription)
        %br

  .group
    %h3 Untagged Feeds

    - @subscriptions.each do |subscription|
      - if !subscription.tags.any? && current_user.is_subscribed?(subscription.feed.id)

        = link_to truncate(subscription.feed.title), subscription.feed
        .icon= link_to image_tag("trash.png", alt: "Remove subscription", :id => 'trash'), subscription, method: :delete, data: { :confirm => 'Are you sure?' }

        .icon= link_to image_tag("edit.png", alt: "Edit tags", :id => 'edit'), edit_subscription_path(subscription)
        %br

%h3= link_to 'View Bookmarks', bookmarks_path

app/views/subscriptions/edit.html.haml
= render 'form'

app/views/subscriptions/index.html.haml
= render @subscriptions

app/views/subscriptions/new.html.haml
%h1 New subscription

= render 'form'

= link_to 'Back', subscriptions_path

app/views/subscriptions/tagged.html.haml
%h1 Listing subscriptions

%table
  %tr
    %th User ID
    %th Feed ID
    %th

  - @subscriptions.each do |subscription|
    %tr
      %td= subscription.user_id
      %td= subscription.feed_id
      - if subscription.tags.any?
        - subscription.tags.each do |tag|
          %td= link_to tag.name, tagged_url(:tag => tag.name)
      %td= link_to 'Show', subscription
      %td= link_to 'Edit', edit_subscription_path(subscription)
      %td= link_to 'Destroy', subscription, method: :delete, data: { :confirm => 'Are you sure?' }



= link_to 'New Subscription', new_subscription_path