config/routes.rb
CantineApp::Application.routes.draw do

  root to: 'feeds#index'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :entries
  resources :read_entries
  resources :feeds
  resources :users
  resources :subscriptions
  resources :bookmarks

  post 'feeds/:id', to: 'feeds#subscribe', as: :feeds_subscribe

  get 'entries/:id/bookmark', to: 'entries#bookmark', as: :entries_bookmark
  get 'entries/:id/mark_as_read', to: 'entries#mark_as_read', as: :entries_mark_as_read
  get 'feeds/:id/update_entries', to: 'feeds#update_entries', as: :feeds_update_entries

  get 'tagged', to: 'subscriptions#tagged', :as => 'tagged'

  resources :entries do
  get 'page/:page', action: :index, on: :collection
  end

end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Canteen - Feed Yourself
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body

    .container

      #topbar
        =link_to image_tag("logo.png", alt: "Canteen Logo", :id => 'logo'), feeds_path
        #topbarlinks
          - if current_user
            = link_to "My Profile", user_path(current_user.id)
          &nbsp;
          - if current_user
            = link_to "Logout", destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure you want to logout?'}

        #search
          - if current_user
            = form_tag feeds_path, method: :get do
              = text_field_tag :q, nil, placeholder: "Feeds, Entries, Users..."
              %span{:class => "submitbuttontop"}
                = submit_tag "Go"

      #sidebar
        - if current_user
          #newsubscriptionbutton
            = form_tag feeds_path, method: :post do
              - if @feed.errors.any?
                #error_explanation
                  %h2= "#{pluralize(@feed.errors.count, "error")} prohibited this feed from being saved:"
                  %ul
                    - @feed.errors.full_messages.each do |msg|
                      %li= msg

              = text_field_tag :url, nil, placeholder: "Enter feed url"
              %span{:class => "submitbuttonsideplus"}
                = submit_tag '+'
          %h3
            = link_to 'All Entries', entries_path
            %span -
            = link_to 'Only Unread', entries_path(read: true)
          = render('subscriptions/subscription.html.haml')

        - else
          - unless content_for?(:sidebar)
            = render('devise/sessions/new.html.haml')

          = yield(:sidebar)

       
          

      #reader
        = yield